# Book settings
title: My sample book
author: The Jupyter Book Community
logo: logo.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force  # Ensure notebooks are executed during the build

# Add Jupyter Sphinx extension for rendering notebooks
sphinx:
  extensions:
    - jupyter_sphinx
    - myst_nb  # Ensure myst_nb extension is included for Jupyter notebooks

# Add myst_nb specific settings
myst_nb:
  execution_cache_path: "_build/.cache"  # Set a path for the cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# Ensure correct builder for HTML output
html:
  builder: jupyter_sphinx
